IMPORTING THE LIBRARIES


In [31]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [32]:
tf.__version__   # checking tensorflow version

'2.17.0'

IMPORTING DATASET

In [33]:
dataset = pd.read_csv('/content/American Express.csv')

In [34]:
dataset.head()

Credit Score  Geography  Gender   Age  Customer Since  Current Account  \
0         553.0      Delhi  Female  45.0             4.0            0.000   
1         447.0  Bengaluru    Male  31.0             7.0            0.000   
2         501.0      Delhi  Female  32.0             2.0            0.000   
3         428.0      Delhi    Male  51.0             3.0            0.000   
4         492.0      Delhi  Female  57.0             6.0      1912681.501   

   Num of products  UPI Enabled  Estimated Yearly Income  Closed  
0              4.0          1.0                 274150.0     0.0  
1              4.0          1.0                 519360.0     0.0  
2              4.0          1.0                 545501.0     0.0  
3              4.0          1.0                  86868.0     0.0  
4              2.0          1.0                 518680.0     0.0

In [35]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9929 entries, 0 to 9928
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Credit Score             9927 non-null   float64
 1   Geography                9927 non-null   object 
 2   Gender                   9927 non-null   object 
 3   Age                      9927 non-null   float64
 4   Customer Since           9927 non-null   float64
 5   Current Account          9927 non-null   float64
 6   Num of products          9927 non-null   float64
 7   UPI Enabled              9927 non-null   float64
 8   Estimated Yearly Income  9927 non-null   float64
 9   Closed                   9927 non-null   float64
dtypes: float64(8), object(2)
memory usage: 775.8+ KB


In [36]:
dataset.describe()

Credit Score          Age  Customer Since  Current Account  \
count   9927.000000  9927.000000     9927.000000     9.927000e+03   
mean     529.465599    45.666163        4.417447     9.839860e+05   
std       78.610089    16.100517        2.392987     8.407988e+05   
min      285.000000    17.000000        0.000000     0.000000e+00   
25%      475.000000    35.000000        3.000000     0.000000e+00   
50%      531.000000    42.000000        4.000000     1.159221e+06   
75%      584.000000    53.000000        7.000000     1.655112e+06   
max      692.000000   137.000000        8.000000     3.985304e+06   

       Num of products  UPI Enabled  Estimated Yearly Income       Closed  
count      9927.000000  9927.000000              9927.000000  9927.000000  
mean          3.029314     0.704946            274356.781505     0.204291  
std           1.081528     0.456090            157578.700489     0.403203  
min           2.000000     0.000000                32.000000     0.000000  
25%           2.000000     0.000000            139890.500000     0.000000  
50%           2.000000     1.000000            274533.000000     0.000000  
75%           4.000000     1.000000            409437.000000     0.000000  
max           7.000000     1.000000            547947.000000     1.000000

In [37]:
dataset.tail()

Credit Score  Geography  Gender   Age  Customer Since  Current Account  \
9924         627.0     Mumbai  Female  42.0             4.0     1.893594e+06   
9925         600.0  Bengaluru  Female  51.0             0.0     9.031778e+05   
9926         553.0      Delhi    Male  75.0             7.0     0.000000e+00   
9927           NaN        NaN     NaN   NaN             NaN              NaN   
9928           NaN        NaN     NaN   NaN             NaN              NaN   

      Num of products  UPI Enabled  Estimated Yearly Income  Closed  
9924              4.0          0.0                 494067.0     0.0  
9925              2.0          1.0                 109375.0     1.0  
9926              4.0          1.0                 180031.0     0.0  
9927              NaN          NaN                      NaN     NaN  
9928              NaN          NaN                      NaN     NaN

In [38]:
dataset.dropna(inplace=True) #removing missing values and null values

In [39]:
dataset.tail()

Credit Score  Geography  Gender   Age  Customer Since  Current Account  \
9922         594.0  Bengaluru    Male  28.0             6.0     0.000000e+00   
9923         557.0  Bengaluru    Male  59.0             3.0     8.050490e+05   
9924         627.0     Mumbai  Female  42.0             4.0     1.893594e+06   
9925         600.0  Bengaluru  Female  51.0             0.0     9.031778e+05   
9926         553.0      Delhi    Male  75.0             7.0     0.000000e+00   

      Num of products  UPI Enabled  Estimated Yearly Income  Closed  
9922              4.0          1.0                 394810.0     0.0  
9923              2.0          0.0                  58163.0     1.0  
9924              4.0          0.0                 494067.0     0.0  
9925              2.0          1.0                 109375.0     1.0  
9926              4.0          1.0                 180031.0     0.0

In [40]:
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [41]:
print(X)

[[553.0 'Delhi' 'Female' ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 'Male' ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 'Female' ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 'Female' ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 'Female' ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 'Male' ... 4.0 1.0 180031.0]]


LABEL ENCODING

In [42]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [43]:
print(X)

[[553.0 'Delhi' 0 ... 4.0 1.0 274150.0]
 [447.0 'Bengaluru' 1 ... 4.0 1.0 519360.0]
 [501.0 'Delhi' 0 ... 4.0 1.0 545501.0]
 ...
 [627.0 'Mumbai' 0 ... 4.0 0.0 494067.0]
 [600.0 'Bengaluru' 0 ... 2.0 1.0 109375.0]
 [553.0 'Delhi' 1 ... 4.0 1.0 180031.0]]


ONE-HOT ENCODING

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [45]:
print(X)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 0.0 1.0 ... 4.0 0.0 494067.0]
 [1.0 0.0 0.0 ... 2.0 1.0 109375.0]
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]]


SPLITTING DATASET INTO TESTING AND TRAINING SET

In [46]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [47]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [48]:
print(X)

[[0.0 1.0 0.0 ... 4.0 1.0 274150.0]
 [1.0 0.0 0.0 ... 4.0 1.0 519360.0]
 [0.0 1.0 0.0 ... 4.0 1.0 545501.0]
 ...
 [0.0 0.0 1.0 ... 4.0 0.0 494067.0]
 [1.0 0.0 0.0 ... 2.0 1.0 109375.0]
 [0.0 1.0 0.0 ... 4.0 1.0 180031.0]]


ANN

In [49]:
ann = tf.keras.models.Sequential()

ADDING INPUT AND FIRST HIDDEN LAYER

In [50]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

ADDING SECOND HIDDEN LAYER

In [51]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

ADDING OUTPUT LAYER

In [52]:
ann.add(tf.keras.layers.Dense(units=1, activation ='sigmoid'))

ANN TRANING

In [53]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics= ['accuracy'])

In [55]:
ann.fit(X_train, y_train, batch_size = 32,epochs = 120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8165 - loss: 0.4099
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8334 - loss: 0.3876
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8228 - loss: 0.4081
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8257 - loss: 0.3998
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8342 - loss: 0.3874
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8345 - loss: 0.3816
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8351 - loss: 0.3823
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3696
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8470 - loss: 0.3720
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8418 - loss: 0.3718
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8480 - loss: 0.3675
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

SINGEL PREDICTION

In [56]:
print(ann.predict(sc.transform([[0.0,1.0,0.0,501,0,32,2,0.0,4,1,545501]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
[[False]]


PREDICTION ON TEST

In [57]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0. 1.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 1.]
 [0. 0.]
 [1. 1.]]


CONFUSION MATRIX


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1498   75]
 [ 214  199]]


0.8544813695871097